### ISSUE TITLE
SDL Error during build

### ISSUE THREAD

**Issue by kazgaroth011** [fire-eggs/CivOne#107]
Trying to get the project running after a long time in Visual studio code and I get this SDL error.

![error](https://user-images.githubusercontent.com/21365802/64376830-72d04880-d029-11e9-90e5-d74ab755a181.jpg)

I seem to recall having this problem before but somehow I solved it. Well here it is again.
(I installed all the stuff SWY mentions in the page Wiki)

**Comment by fire-eggs** [comment]
One of the failures of my project setup.

The SDL2.DLL file needs to be in the binary output directory. Specifically, in
`<root>\runtime\sdl\bin\Debug\netcoreapp2.1`, where <root> is your base folder.  Or Release instead of Debug, when building in release mode.

Sorry for the delay in answering, I'm travelling.

**Comment by kazgaroth011** [comment]
OK it works now.
